name: Build C++ Project

on:
  push:
    branches:
      - master

env:
  CXX: "clang++"
  CXXFLAGS: "-Wall -Wextra -std=c++20 -O1 -g -fsanitize=address -fsanitize=leak -fno-omit-frame-pointer"
  LDFLAGS: "-g -fsanitize=address -fsanitize=leak"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get install -y clang

    - name: Build project
      run: make
